//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avtoprokat.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AvtoprokatEntities : DbContext
    {
        public AvtoprokatEntities()
            : base("name=AvtoprokatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<car> car { get; set; }
        public virtual DbSet<discount> discount { get; set; }
        public virtual DbSet<make_car> make_car { get; set; }
        public virtual DbSet<model_car> model_car { get; set; }
        public virtual DbSet<registration_plates> registration_plates { get; set; }
        public virtual DbSet<rental_car> rental_car { get; set; }
        public virtual DbSet<renter> renter { get; set; }
    }
}
