USE [master]
GO

/****** Object:  Database [4_IS_1_Ermolaev_Avtoprokat]    Script Date: 25.12.2021 12:59:15 ******/
CREATE DATABASE [4_IS_1_Ermolaev_Avtoprokat]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'4_IS_1_Ermmolaev_Avtoprokat', FILENAME = N'D:\MSSQL\4_IS_1_Ermmolaev_Avtoprokat.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'4_IS_1_Ermmolaev_Avtoprokat_log', FILENAME = N'D:\MSSQL\4_IS_1_Ermmolaev_Avtoprokat_log.ldf' , SIZE = 1280KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [4_IS_1_Ermolaev_Avtoprokat].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [4_IS_1_Ermolaev_Avtoprokat] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [4_IS_1_Ermolaev_Avtoprokat] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [4_IS_1_Ermolaev_Avtoprokat] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [4_IS_1_Ermolaev_Avtoprokat] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [4_IS_1_Ermolaev_Avtoprokat] SET ARITHABORT OFF 
GO

ALTER DATABASE [4_IS_1_Ermolaev_Avtoprokat] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [4_IS_1_Ermolaev_Avtoprokat] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [4_IS_1_Ermolaev_Avtoprokat] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [4_IS_1_Ermolaev_Avtoprokat] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [4_IS_1_Ermolaev_Avtoprokat] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [4_IS_1_Ermolaev_Avtoprokat] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [4_IS_1_Ermolaev_Avtoprokat] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [4_IS_1_Ermolaev_Avtoprokat] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [4_IS_1_Ermolaev_Avtoprokat] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [4_IS_1_Ermolaev_Avtoprokat] SET  DISABLE_BROKER 
GO

ALTER DATABASE [4_IS_1_Ermolaev_Avtoprokat] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [4_IS_1_Ermolaev_Avtoprokat] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [4_IS_1_Ermolaev_Avtoprokat] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [4_IS_1_Ermolaev_Avtoprokat] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [4_IS_1_Ermolaev_Avtoprokat] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [4_IS_1_Ermolaev_Avtoprokat] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [4_IS_1_Ermolaev_Avtoprokat] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [4_IS_1_Ermolaev_Avtoprokat] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [4_IS_1_Ermolaev_Avtoprokat] SET  MULTI_USER 
GO

ALTER DATABASE [4_IS_1_Ermolaev_Avtoprokat] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [4_IS_1_Ermolaev_Avtoprokat] SET DB_CHAINING OFF 
GO

ALTER DATABASE [4_IS_1_Ermolaev_Avtoprokat] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [4_IS_1_Ermolaev_Avtoprokat] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [4_IS_1_Ermolaev_Avtoprokat] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [4_IS_1_Ermolaev_Avtoprokat] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [4_IS_1_Ermolaev_Avtoprokat] SET QUERY_STORE = OFF
GO

ALTER DATABASE [4_IS_1_Ermolaev_Avtoprokat] SET  READ_WRITE 
GO

